## Numpy

In [1]:
import numpy as np

In [2]:
np.__file__

'/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'

## NumPy Arrays(ndarray)

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [11]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=complex)

In [10]:
type(matrix[0][0])

numpy.int64

In [12]:
matrix

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [13]:
ndarray = np.array([1, 2, 3], dtype=np.uint8) # unsigned + - integer 8bit(0~255)

In [14]:
ndarray

array([1, 2, 3], dtype=uint8)

In [15]:
ndarray = np.array([1, 2, 3], dtype=np.float32)

In [16]:
ndarray

array([1., 2., 3.], dtype=float32)

In [18]:
ndarray.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

## numarrayの演算

In [20]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [21]:
array1 + array2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [23]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [24]:
array1 + array2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [25]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [26]:
ndarray + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Shape

In [29]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
ndarray.shape

(3, 2)

In [32]:
ndarray.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
ndarray1 = np.array([1, 2, 3])
ndarray2 = np.array([[1, 2, 3]])

In [34]:
ndarray1

array([1, 2, 3])

In [36]:
ndarray1.shape

(3,)

In [35]:
ndarray2

array([[1, 2, 3]])

In [37]:
ndarray2.shape

(1, 3)

In [44]:
expand_ndarray = np.expand_dims(ndarray1, axis=1)

In [45]:
expand_ndarray.shape

(3, 1)

In [46]:
np.squeeze(expand_ndarray)

array([1, 2, 3])

In [49]:
ndarray = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ndarray.shape

(3, 3)

In [50]:
ndarray.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## IndexingとSlicing

In [52]:
ndarray = np.array([[1, 2], [3, 4], [5, 6]])
ndarray

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
ndarray[0, 1]

2

In [58]:
ndarray = np.array([1, 2, 3, 4])
ndarray

array([1, 2, 3, 4])

In [59]:
ndarray[1:3]

array([2, 3])

In [60]:
ndarray[:3]

array([1, 2, 3])

In [62]:
ndarray = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14, 15, 16]])

In [63]:
ndarray

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [65]:
ndarray[:3, 2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [66]:
ndarray[:3][2:]

array([[ 9, 10, 11, 12]])

## np.arange(),np.linespace(),np.logspace()

In [68]:
np.arange(3, 15, 2)

array([ 3,  5,  7,  9, 11, 13])

In [69]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [79]:
np.logspace(0, 3, 10, endpoint=False) 

array([  1.        ,   1.99526231,   3.98107171,   7.94328235,
        15.84893192,  31.6227766 ,  63.09573445, 125.89254118,
       251.18864315, 501.18723363])

In [80]:
np.linspace(0, 3, 10, endpoint=False)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

## np.zeros(shape)

In [81]:
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.zeros(3)

array([0., 0., 0.])

## np.ones(shape)

In [87]:
shape = (5, 4)
np.ones(shape)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [88]:
np.ones(3)

array([1., 1., 1.])

In [89]:
np.ones((5, 4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

## np.eye()

In [90]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [91]:
np.eye(3, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## np.random

In [96]:
np.random.rand(3, 4)

array([[0.74402168, 0.57670095, 0.97410135, 0.44428567],
       [0.51438981, 0.81576315, 0.92222652, 0.08469594],
       [0.02547873, 0.14452187, 0.48913198, 0.1824594 ]])

In [98]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [99]:
np.random.rand()

0.7203244934421581

In [102]:
np.random.randn(5, 5) #正規分布から値を持ってくる

array([[-0.24937038,  1.46210794, -2.06014071, -0.3224172 , -0.38405435],
       [ 1.13376944, -1.09989127, -0.17242821, -0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918,  1.14472371,  0.90159072,  0.50249434],
       [ 0.90085595, -0.68372786, -0.12289023, -0.93576943, -0.26788808],
       [ 0.53035547, -0.69166075, -0.39675353, -0.6871727 , -0.84520564]])

In [103]:
np.random.normal(0, 1)

-0.671246130836819

In [104]:
np.random.randint(10, 100, (2, 3))

array([[35, 81, 84],
       [72, 56, 42]])

In [111]:
np.random.randint(10)

3

In [107]:
a = [1, 2, 3]
np.random.choice(a)

2

In [108]:
index_pool = np.arange(0, 10, 2)
index_pool

array([0, 2, 4, 6, 8])

In [109]:
idx = np.random.choice(index_pool)

In [115]:
std_norm = np.random.randn(5, 5)
std_norm

array([[-0.1557128 ,  0.57239227,  0.75995548,  0.73568199,  1.01389243],
       [-0.73843118,  0.25770667, -1.13745173,  1.57814135, -0.17511057],
       [-1.72908882, -0.24407447,  0.19307961,  1.24779637, -0.0493205 ],
       [-0.77034792, -0.77405219,  0.61001901, -1.54708101, -0.20476773],
       [-1.46829223,  0.04155277,  0.02683149, -0.641126  , -0.36931625]])

In [128]:
std_norm.max(axis=0)

array([-0.1557128 ,  0.57239227,  0.75995548,  1.57814135,  1.01389243])

In [117]:
np.max(std_norm)

1.5781413451795898

In [118]:
std_norm.min()

-1.7290888221556728

In [119]:
std_norm.argmax()

8

In [120]:
std_norm.flatten()[8]

1.5781413451795898

In [121]:
std_norm.argmin()

10

In [122]:
std_norm.flatten()[10]

-1.7290888221556728

In [123]:
std_norm.mean()

-0.11868495837851677

In [126]:
np.median(std_norm)

-0.15571280359495435

In [127]:
np.std(std_norm)

0.8467596535418399

## 数学で使う便利関数

In [129]:
# 平方根 square root
np.sqrt([1, 2, 3, 4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [130]:
# log (logerithm)
x = np.linspace(1, 10, 10)
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [131]:
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [133]:
# 指数関数　Exponential function
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [134]:
np.e

2.718281828459045

In [137]:
# 合計　Sumation
array = np.arange(1, 11)
np.sum([1, 2, 3])

6

In [138]:
np.sum(array)

55

In [140]:
ndarray = array.reshape(2, 5)
ndarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [141]:
np.sum(ndarray, axis=1)

array([15, 40])

In [142]:
# 絶対値 absolute value
array = np.arange(-10, 0)

In [143]:
np.abs(array)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [144]:
# NaN : Not a Number
np.log(-100)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


nan

In [146]:
type(np.nan)

float

In [147]:
a = None
a is None

True

In [148]:
np.isnan(np.log(-100))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


True

### その他の便利関数

In [149]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.clip(array, 3, 7)

array([3, 3, 3, 3, 4, 5, 6, 7, 7, 7])

In [151]:
np.where(array > 3, 1, 0)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [152]:
ndarray = array.reshape(2, 5)
ndarray[ndarray>3]

array([4, 5, 6, 7, 8, 9])

In [154]:
ndarray > 3

array([[False, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [156]:
(ndarray > 3).all()

False

In [157]:
(ndarray > 3).any()

True

In [158]:
(ndarray > 3).all(axis=0)

array([False, False, False, False,  True])

In [159]:
(ndarray > 3).all(axis=1)

array([False,  True])

In [161]:
# np.unique()
array = np.array([1, 1, 2, 3, 4, 2, 3, 4, 5])
array

array([1, 1, 2, 3, 4, 2, 3, 4, 5])

In [162]:
np.unique(array)

array([1, 2, 3, 4, 5])

In [163]:
np.unique(array, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 2, 2, 1]))

In [165]:
# np.bincount()
np.bincount(array)

array([0, 2, 2, 2, 2, 1])

In [166]:
# np.concatenate(),np.stack()
ndarray_even = np.arange(0, 18, 2).reshape(3, 3)
ndarray_even

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [167]:
ndarray_odd = np.arange(1, 19, 2).reshape(3, 3)
ndarray_odd

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [169]:
np.concatenate([ndarray_even, ndarray_odd])

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [170]:
np.concatenate([ndarray_even, ndarray_odd], axis=1)

array([[ 0,  2,  4,  1,  3,  5],
       [ 6,  8, 10,  7,  9, 11],
       [12, 14, 16, 13, 15, 17]])

In [171]:
np.stack([ndarray_even, ndarray_odd])

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [172]:
_

array([[[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]],

       [[ 1,  3,  5],
        [ 7,  9, 11],
        [13, 15, 17]]])

In [173]:
stacked_array = _

In [174]:
stacked_array.shape

(2, 3, 3)

In [175]:
# np.transpose .T
ndarray = np.random.randn(3, 4)
ndarray

array([[-1.16729452,  0.02454542, -0.98237626, -0.3029153 ],
       [-0.57041883, -0.9307552 , -0.77458086,  0.14652259],
       [-0.85413244, -1.83582581, -1.14010497, -0.5924452 ]])

In [176]:
ndarray.shape

(3, 4)

In [178]:
np.transpose(ndarray)

array([[-1.16729452, -0.57041883, -0.85413244],
       [ 0.02454542, -0.9307552 , -1.83582581],
       [-0.98237626, -0.77458086, -1.14010497],
       [-0.3029153 ,  0.14652259, -0.5924452 ]])

In [179]:
transpose_ndarray = _

In [180]:
transpose_ndarray.shape

(4, 3)

In [181]:
ndarray.T

array([[-1.16729452, -0.57041883, -0.85413244],
       [ 0.02454542, -0.9307552 , -1.83582581],
       [-0.98237626, -0.77458086, -1.14010497],
       [-0.3029153 ,  0.14652259, -0.5924452 ]])

In [183]:
# np.save('path',array), np.load('path')
ndarray = np.random.randn(3, 4, 5)
ndarray.shape

(3, 4, 5)

In [184]:
np.save('sanple_ndarray.npy', ndarray)

In [186]:
loaded_ndarray = np.load('sanple_ndarray.npy')
loaded_ndarray.shape

(3, 4, 5)

In [188]:
dictionary = {
    'id': 123456,
    'image': ndarray
}

In [189]:
np.save('sample_dict.npy', dictionary)

In [197]:
loaded_dict = np.load('sample_dict.npy', allow_pickle=True)[()]

In [198]:
loaded_dict

{'id': 123456,
 'image': array([[[ 0.88200328,  0.77883804,  1.49903239,  1.54290932,
          -0.44773169],
         [-1.77769234, -1.79183523, -1.00506543, -0.40037634,
           0.53625837],
         [ 1.29978471,  0.09418039, -0.28316929, -0.39571274,
          -0.71243197],
         [-1.35634559, -0.8377157 , -0.49391067, -0.14144644,
          -0.87467077]],
 
        [[ 1.0468758 ,  0.26983708,  0.40891533, -0.33733696,
           0.11074674],
         [ 0.57440022,  0.68663023,  1.72377011, -2.42197115,
          -1.50118296],
         [ 0.04639887, -0.0765315 ,  0.84209188,  0.36740036,
          -0.51129395],
         [-0.73545714, -0.26085211,  1.17371236,  0.26465216,
          -1.5056096 ]],
 
        [[ 1.05782505,  0.17529574,  1.75793296, -0.72760633,
           0.51496913],
         [-0.69591798,  1.77864084,  0.91488862,  0.81574597,
           0.71141615],
         [-0.1713099 , -0.20347205,  0.42216704,  1.35688401,
          -0.21122305],
         [ 1.32271438, -

In [195]:
a = np.array({'a': 1})

In [196]:
a[()]

{'a': 1}